### ISSUE TITLE
Gffread takes all features

### ISSUE THREAD

**Issue by chriswyatt1** [Eco-Flow/synteny#37]
Currently gffread takes all features in the gff, coding and non-coding (+ psuedogenes). 

This may not be the required behaviour. 

We could change this in the gffread option -C (coding only) with flags, but it may not work if the gff does not contain this information (as some don't), so at the moment it seems fair to take all features form the gff, but we should warn the user, that is what is happening.

**Comment by SimonDMurray** [comment]
Hi @chriswyatt1,

I have a solution but it requires you editing the magical perl scripts I do not understand 😝 

Here are the steps:
1) Edit the `conf/modules.config` to include:
```
withName: 'GFFREAD' {
        ext.args   = { [
                    params.gffread_coding         != null ? "-C" : '',
            ].join(' ').trim() }
    }
```
This sets up the parameter that will translate to `-C`

2) Edit `nextflow.config` so that the parameter is set by default to null: `gffread_coding             = null` 
3) Edit `modules/local/gffread.nf` to include:
```
script:
    def args = task.ext.args ?: ''
    """
    perl ${projectDir}/bin/gffread_unzip.pl ${sample_id} ${fasta} ${gff}
```    
Now this is the tricky bit. What that will do when you specify the parameter is pass `-C` as a third argument to the perl script i.e. `perl gffread_unzip.pl Drosophila_santomea genome.fna.gz Drosophila_santomea.longest.gff3 -C`. So the perl script needs to be changes to handle a third argument that doesn't need to be set but when is set to `-C` (or whatever you prefer) then `-C` is passed to gffread.

Does that make sense?
